name: Basic checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yaml

  dry-run-ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
      - name: Ansible syntax check
        run: ansible-playbook -i inventory.ini site.yml --syntax-check
